version: '3.8'

services:
  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env.default
      - .env
    restart: always

  blockstorage:
    build:
      dockerfile: blockstorage.dockerfile
    env_file:
      - .env.default
      - .env
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
    restart: always
    depends_on:
      - cassandra

  metastorage:
    build:
      dockerfile: metadata.dockerfile
    ports:
      - "9090:9090"
    restart: always
    env_file:
      - .env.default
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fileserver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db

  web:
    build:
      dockerfile: web.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.default
      - .env
    environment:
      - BLOCK_STORAGE_HOST=blockstorage
      - META_STORAGE_HOST=metastorage
    restart: always
    depends_on:
      - blockstorage

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"