version: '3.8'

services:
  blockstorage:
    build:
      dockerfile: blockstorage.dockerfile
    ports:
      - "9090:9090"
    restart: always

  web:
    build:
      dockerfile: web.dockerfile
    ports:
      - "8080:8080"
    environment:
      - BLOCK_STORAGE_HOST=blockstorage
    restart: always